"""ClaimType

Revision ID: 02c3abc18f07
Revises: 7369cbf41001
Create Date: 2021-12-06 12:31:25.807471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c3abc18f07'
down_revision = '7369cbf41001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_history', sa.Column('claim_type', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_history', 'claim_type')
    # ### end Alembic commands ###
