"""UpdateAirdropTable

Revision ID: 03431fb8fd1d
Revises: 1c6bb2fd25d5
Create Date: 2021-12-21 15:07:53.209448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03431fb8fd1d'
down_revision = '1c6bb2fd25d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop', sa.Column('stakable_token_name', sa.VARCHAR(length=50), nullable=True))
    op.add_column('airdrop', sa.Column('staking_contract_address', sa.VARCHAR(length=50), nullable=True))
    op.add_column('airdrop', sa.Column('token_address', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('airdrop', 'address')
    op.add_column('claim_history', sa.Column('blockchain_method', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('claim_history', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_history', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('claim_history', 'blockchain_method')
    op.add_column('airdrop', sa.Column('address', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('airdrop', 'token_address')
    op.drop_column('airdrop', 'staking_contract_address')
    op.drop_column('airdrop', 'stakable_token_name')
    # ### end Alembic commands ###
