"""UpdateRewardsAwardedAsVarchar

Revision ID: 0f7c4d8f3b8f
Revises: 62f9e82adaa6
Create Date: 2022-01-14 17:43:44.511750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7c4d8f3b8f'
down_revision = '62f9e82adaa6'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('ALTER TABLE airdrop.user_rewards MODIFY COLUMN rewards_awarded VARCHAR(50) NOT NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
