"""AddreceiptOnRegistrationTable

Revision ID: 1468fd5ca2be
Revises: 3dd7097453f8
Create Date: 2022-02-24 22:33:14.628454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1468fd5ca2be'
down_revision = '3dd7097453f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('receipt_generated', sa.VARCHAR(length=250), nullable=True))
    op.create_index(op.f('ix_user_registrations_receipt_generated'), 'user_registrations', ['receipt_generated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registrations_receipt_generated'), table_name='user_registrations')
    op.drop_column('user_registrations', 'receipt_generated')
    # ### end Alembic commands ###
