"""Adding columns for rewards computation

Revision ID: 19445f9727ff
Revises: 1d6df6000e39
Create Date: 2021-12-21 14:48:19.208080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19445f9727ff'
down_revision = '1d6df6000e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rewards_audit',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_id', sa.BIGINT(), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance', sa.BIGINT(), nullable=False),
    sa.Column('staked', sa.BIGINT(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=10, scale=5), nullable=False),
    sa.Column('rewards_awarded', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_guid', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop.row_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('airdrop_window_id', 'address')
    )
    op.create_index(op.f('ix_user_rewards_audit_address'), 'user_rewards_audit', ['address'], unique=False)
    op.drop_table('airdrop_window_snapshot_mapping')
    op.add_column('airdrop', sa.Column('rewards_processor', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('airdrop', 'check_eligibility')
    op.add_column('user_balance_snapshot', sa.Column('snapshot_guid', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('user_balance_snapshot', 'snapshot_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_balance_snapshot', sa.Column('snapshot_index', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_balance_snapshot', 'snapshot_guid')
    op.add_column('airdrop', sa.Column('check_eligibility', mysql.BIT(length=1), nullable=True))
    op.drop_column('airdrop', 'rewards_processor')
    op.create_table('airdrop_window_snapshot_mapping',
    sa.Column('row_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('airdrop_window_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('snapshot_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop.row_id'], name='airdrop_window_snapshot_mapping_ibfk_1', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], name='airdrop_window_snapshot_mapping_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_rewards_audit_address'), table_name='user_rewards_audit')
    op.drop_table('user_rewards_audit')
    # ### end Alembic commands ###
