"""Adding columns for rewards computation

Revision ID: 1d6df6000e39
Revises: 5353f0a8d078
Create Date: 2021-12-21 13:41:29.418932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d6df6000e39'
down_revision = '5353f0a8d078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop_window_snapshot_mapping',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_id', sa.BIGINT(), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('snapshot_index', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop.row_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.add_column('airdrop_window', sa.Column('last_snapshot_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('user_rewards', sa.Column('score', sa.DECIMAL(precision=10, scale=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rewards', 'score')
    op.drop_column('airdrop_window', 'last_snapshot_at')
    op.drop_table('airdrop_window_snapshot_mapping')
    # ### end Alembic commands ###
