"""UpdateColsOnAirdrop

Revision ID: 22b0f76536c4
Revises: 1c6bb2fd25d5
Create Date: 2021-12-21 08:30:16.071449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22b0f76536c4'
down_revision = '1c6bb2fd25d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop', sa.Column('token_address', sa.VARCHAR(length=128), nullable=True))
    op.add_column('claim_history', sa.Column('blockchain_method', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('claim_history', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_history', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('claim_history', 'blockchain_method')
    op.drop_column('airdrop', 'token_address')
    # ### end Alembic commands ###
