"""AddBlockNumberOnRegistrationTable

Revision ID: 22cd02190a1c
Revises: 7ebcbe8dcfa1
Create Date: 2022-07-26 10:57:29.400285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22cd02190a1c'
down_revision = '7ebcbe8dcfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop_window', sa.Column('minimum_stake_amount', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airdrop_window', 'minimum_stake_amount')
    # ### end Alembic commands ###
