"""AirdropWindowWithID

Revision ID: 29247718ca97
Revises: 7d4f17a20f41
Create Date: 2021-11-02 11:45:31.831189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29247718ca97'
down_revision = '7d4f17a20f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop_window', sa.Column('airdrop_window_id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint('uq_airdrop_id', 'airdrop_window', ['airdrop_window_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_airdrop_id', 'airdrop_window', type_='unique')
    op.drop_column('airdrop_window', 'airdrop_window_id')
    # ### end Alembic commands ###
