"""AirdopWindowOrder

Revision ID: 298dcaa32b11
Revises: 7d4f17a20f41
Create Date: 2021-11-09 09:18:04.393451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298dcaa32b11'
down_revision = '7d4f17a20f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop_window', sa.Column('airdrop_window_order', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airdrop_window', 'airdrop_window_order')
    # ### end Alembic commands ###
