"""AddAirdropIdOnNotificationsTable

Revision ID: 3dd7097453f8
Revises: 848d9def72dc
Create Date: 2022-02-22 13:46:59.185179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dd7097453f8'
down_revision = '848d9def72dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('airdrop_id', sa.BIGINT(), nullable=True))
    op.drop_index('email', table_name='user_notifications')
    op.create_unique_constraint(None, 'user_notifications', ['email', 'airdrop_id'])
    op.alter_column('user_rewards_audit', 'rewards_awarded',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_rewards_audit', 'rewards_awarded',
               existing_type=sa.VARCHAR(length=50),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    op.drop_constraint(None, 'user_notifications', type_='unique')
    op.create_index('email', 'user_notifications', ['email'], unique=True)
    op.drop_column('user_notifications', 'airdrop_id')
    # ### end Alembic commands ###
