"""RemoveIsEligibleColFromUserRegTable

Revision ID: 5687a676e889
Revises: 7d4f17a20f41
Create Date: 2021-11-04 11:54:08.098151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5687a676e889'
down_revision = '7d4f17a20f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_registrations', 'is_eligible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('is_eligible', mysql.BIT(length=1), nullable=True))
    # ### end Alembic commands ###
