"""Update UserRegistration model address length

Revision ID: 5a43bfd1e14c
Revises: b06d405fddac
Create Date: 2025-02-24 15:17:29.036097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a43bfd1e14c'
down_revision = 'b06d405fddac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_registrations', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_registrations', 'address',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
