"""Removed constraint on audit table

Revision ID: 62f9e82adaa6
Revises: 84b3a41147f0
Create Date: 2021-12-23 07:57:49.890382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f9e82adaa6'
down_revision = '84b3a41147f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_rewards_audit_ibfk_2', 'user_rewards_audit', type_='foreignkey')
    op.drop_constraint('user_rewards_audit_ibfk_1', 'user_rewards_audit', type_='foreignkey')
    op.drop_index('airdrop_window_id', table_name='user_rewards_audit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_rewards_audit_ibfk_1', 'user_rewards_audit', 'airdrop', ['airdrop_id'], ['row_id'], ondelete='RESTRICT')
    op.create_foreign_key('user_rewards_audit_ibfk_2', 'user_rewards_audit', 'airdrop_window', ['airdrop_window_id'], ['row_id'], ondelete='RESTRICT')
    op.create_index('airdrop_window_id', 'user_rewards_audit', ['airdrop_window_id', 'address'], unique=True)
    # ### end Alembic commands ###
