"""DropStake_token_nameFromAirdropTable

Revision ID: 6c789553d829
Revises: 0b1a68c83ffb
Create Date: 2022-03-01 21:28:48.623876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c789553d829'
down_revision = '0b1a68c83ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airdrop', 'stakable_token_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop', sa.Column('stakable_token_name', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
