"""Adding columns for rewards computation

Revision ID: 6ca95583c82b
Revises: 19445f9727ff
Create Date: 2021-12-21 16:25:16.401580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca95583c82b'
down_revision = '19445f9727ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_balance_snapshot', sa.Column('total', sa.BIGINT(), nullable=False))
    op.add_column('user_rewards_audit', sa.Column('comment', sa.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rewards_audit', 'comment')
    op.drop_column('user_balance_snapshot', 'total')
    # ### end Alembic commands ###
