"""Update address length for all models

Revision ID: 6d18e55c5d9c
Revises: 5a43bfd1e14c
Create Date: 2025-02-28 13:24:57.780006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d18e55c5d9c'
down_revision = '5a43bfd1e14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_history', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('user_balance_snapshot', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('user_pending_rewards', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('user_rewards', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('user_rewards_audit', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_rewards_audit', 'address',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user_rewards', 'address',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user_pending_rewards', 'address',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user_balance_snapshot', 'address',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('claim_history', 'address',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
