"""AirdropRulesCol

Revision ID: 7214234a0285
Revises: 060c7d29a89c
Create Date: 2021-10-21 08:15:00.841609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7214234a0285'
down_revision = '060c7d29a89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop', sa.Column('airdrop_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airdrop', 'airdrop_rules')
    # ### end Alembic commands ###
