"""AddBlockNumberOnRegistrationTable

Revision ID: 72366f6844ea
Revises: f7c7368d577c
Create Date: 2022-04-12 23:44:28.794712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72366f6844ea'
down_revision = 'f7c7368d577c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('user_signature_block_number', sa.BIGINT(), nullable=True))
    op.create_index(op.f('ix_user_registrations_user_signature_block_number'), 'user_registrations', ['user_signature_block_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registrations_user_signature_block_number'), table_name='user_registrations')
    op.drop_column('user_registrations', 'user_signature_block_number')
    # ### end Alembic commands ###
