"""AlterRewardsUserRewardAuditTable

Revision ID: 757175e49ae6
Revises: d2b614d9802b
Create Date: 2022-03-03 16:15:19.124977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757175e49ae6'
down_revision = 'd2b614d9802b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
