"""rename_columns

Revision ID: 7f844b08e3c9
Revises: 384051a9013e
Create Date: 2022-07-01 17:13:09.819412

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f844b08e3c9'
down_revision = '384051a9013e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop', sa.Column('airdrop_processor', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('airdrop', 'rewards_processor')
    op.add_column('user_registrations', sa.Column('signature_details', sa.JSON(), nullable=True))
    op.drop_column('user_registrations', 'signed_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('signed_data', mysql.JSON(), nullable=True))
    op.drop_column('user_registrations', 'signature_details')
    op.add_column('airdrop', sa.Column('rewards_processor', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('airdrop', 'airdrop_processor')
    # ### end Alembic commands ###
