"""CHANGE_columns

Revision ID: 7f844b08e3c9
Revises: 384051a9013e
Create Date: 2022-07-01 17:13:09.819412

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f844b08e3c9'
down_revision = '384051a9013e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands augenerated by Alembic - please adjust! ###
    op.execute("ALTER TABLE airdrop CHANGE COLUMN rewards_processor airdrop_processor VARCHAR(256);")
    op.execute("ALTER TABLE user_registrations CHANGE COLUMN signed_data signature_details JSON;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands augenerated by Alembic - please adjust! ###
    op.execute("ALTER TABLE airdrop CHANGE COLUMN airdrop_processor rewards_processor VARCHAR(256);")
    op.execute("ALTER TABLE user_registrations CHANGE COLUMN signature_details signed_data JSON;")
    # ### end Alembic commands ###
