"""Eligibility Computation

Revision ID: 7fdcc2e22f9b
Revises: 7369cbf41001
Create Date: 2021-12-14 18:45:13.694705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fdcc2e22f9b'
down_revision = '7369cbf41001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop', sa.Column('check_eligibility', mysql.BIT(), nullable=True))
    op.add_column('user_balance_snapshot', sa.Column('snapshot_index', sa.INTEGER(), nullable=False))
    op.add_column('user_balance_snapshot', sa.Column('staked', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_balance_snapshot', 'staked')
    op.drop_column('user_balance_snapshot', 'snapshot_index')
    op.drop_column('airdrop', 'check_eligibility')
    # ### end Alembic commands ###
