"""AddRejectReasonToRegistrations

Revision ID: 905e1aab6d35
Revises: b104e1272d6d
Create Date: 2021-10-28 15:31:17.074138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905e1aab6d35'
down_revision = 'b104e1272d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('reject_reason', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_registrations', 'reject_reason')
    # ### end Alembic commands ###
