"""AlterRewardsOnSnapShotTable

Revision ID: 9c0ce1942023
Revises: 2abbd40b9025
Create Date: 2022-03-03 17:04:56.088786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c0ce1942023'
down_revision = '2abbd40b9025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_balance_snapshot', 'balance',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.DECIMAL(precision=64, scale=0),
               existing_nullable=False)
    op.alter_column('user_balance_snapshot', 'staked',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.DECIMAL(precision=64, scale=0),
               existing_nullable=False)
    op.alter_column('user_balance_snapshot', 'total',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.DECIMAL(precision=64, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_balance_snapshot', 'total',
               existing_type=sa.DECIMAL(precision=64, scale=0),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    op.alter_column('user_balance_snapshot', 'staked',
               existing_type=sa.DECIMAL(precision=64, scale=0),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    op.alter_column('user_balance_snapshot', 'balance',
               existing_type=sa.DECIMAL(precision=64, scale=0),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    # ### end Alembic commands ###
