"""Update claim_history table.

Revision ID: b06d405fddac
Revises: 22cd02190a1c
Create Date: 2022-08-09 09:29:45.507300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06d405fddac'
down_revision = '22cd02190a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_history', sa.Column('transaction_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_history', 'transaction_details')
    # ### end Alembic commands ###
