"""AddClaimedONHistory

Revision ID: b104e1272d6d
Revises: 7214234a0285
Create Date: 2021-10-26 12:31:59.607091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b104e1272d6d'
down_revision = '7214234a0285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_history', sa.Column('claimed_on', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_history', 'claimed_on')
    # ### end Alembic commands ###
