"""add_pending_transaction_table

Revision ID: bdb6264c06a7
Revises: 55e3aad4e51e
Create Date: 2025-03-28 14:18:25.494716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdb6264c06a7'
down_revision = '55e3aad4e51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_transactions',
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=250), nullable=False),
    sa.Column('reject_reason', sa.JSON(), nullable=True),
    sa.Column('receipt_generated', sa.VARCHAR(length=250), nullable=True),
    sa.Column('tx_hash', sa.VARCHAR(length=250), nullable=False),
    sa.Column('signature_details', sa.JSON(), nullable=True),
    sa.Column('user_signature_block_number', sa.BIGINT(), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('airdrop_window_id', 'address')
    )
    op.create_index('snapshot_guid_idx', 'user_balance_snapshot', ['snapshot_guid'], unique=False)
    op.add_column('user_registrations', sa.Column('tx_hash', sa.VARCHAR(length=250), nullable=True))
    op.create_index(op.f('ix_user_registrations_tx_hash'), 'user_registrations', ['tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registrations_tx_hash'), table_name='user_registrations')
    op.drop_column('user_registrations', 'tx_hash')
    op.drop_index('snapshot_guid_idx', table_name='user_balance_snapshot')
    op.drop_table('pending_transactions')
    # ### end Alembic commands ###
