"""AddAirdropIDOnRewards

Revision ID: ca5783518bb1
Revises: c77ed315d134
Create Date: 2021-10-14 14:01:09.151062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5783518bb1'
down_revision = 'c77ed315d134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_rewards', sa.Column('airdrop_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'user_rewards', 'airdrop', ['airdrop_id'], ['row_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rewards', type_='foreignkey')
    op.drop_column('user_rewards', 'airdrop_id')
    # ### end Alembic commands ###
