"""add staking, payment parts

Revision ID: ce8542214622
Revises: bdb6264c06a7
Create Date: 2025-04-01 16:18:43.662768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8542214622'
down_revision = 'bdb6264c06a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('payment_part', sa.VARCHAR(length=250), nullable=True))
    op.add_column('user_registrations', sa.Column('staking_part', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_registrations', 'staking_part')
    op.drop_column('user_registrations', 'payment_part')
    # ### end Alembic commands ###
