"""AlterRewardsOnClaimHistoryTable

Revision ID: d2b614d9802b
Revises: 2abbd40b9025
Create Date: 2022-03-03 16:14:16.198074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b614d9802b'
down_revision = '2abbd40b9025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
