"""AddSignatureOnRegistrationTable

Revision ID: f7c7368d577c
Revises: 49b4b7cca932
Create Date: 2022-03-31 14:40:45.126366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c7368d577c'
down_revision = '49b4b7cca932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('user_signature', sa.VARCHAR(length=250), nullable=True))
    op.create_index(op.f('ix_user_registrations_user_signature'), 'user_registrations', ['user_signature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registrations_user_signature'), table_name='user_registrations')
    op.drop_column('user_registrations', 'user_signature')
    # ### end Alembic commands ###
