"""AddColumnRegisteredAtOnUserReg

Revision ID: 2d1f89d6efd0
Revises: 5bafd29c1ae6
Create Date: 2021-09-28 02:51:43.912460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d1f89d6efd0'
down_revision = '5bafd29c1ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('registered_at', mysql.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_user_registrations_registered_at'), 'user_registrations', ['registered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registrations_registered_at'), table_name='user_registrations')
    op.drop_column('user_registrations', 'registered_at')
    # ### end Alembic commands ###
