"""AirdropTables

Revision ID: 5bafd29c1ae6
Revises: 
Create Date: 2021-09-27 10:31:17.001217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bafd29c1ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('org_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('token_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contract_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('portal_link', sa.VARCHAR(length=256), nullable=True),
    sa.Column('documentation_link', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('github_link_for_contract', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('airdrop_window',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_id', sa.BIGINT(), nullable=False),
    sa.Column('airdrop_window_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('registration_required', mysql.BIT(), nullable=True),
    sa.Column('registration_start_period', mysql.TIMESTAMP(), nullable=False),
    sa.Column('registration_end_period', mysql.TIMESTAMP(), nullable=False),
    sa.Column('snapshot_required', mysql.BIT(), nullable=True),
    sa.Column('first_snapshot_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('claim_start_period', mysql.TIMESTAMP(), nullable=False),
    sa.Column('claim_end_period', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop.row_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('airdropwindow_rules',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('rule', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('claim_history',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_id', sa.BIGINT(), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('claimable_amount', sa.INTEGER(), nullable=False),
    sa.Column('unclaimed_amount', sa.INTEGER(), nullable=False),
    sa.Column('transaction_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop.row_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index(op.f('ix_claim_history_address'), 'claim_history', ['address'], unique=False)
    op.create_table('user_balance_snapshot',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('balance', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('user_registrations',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_eligible', mysql.BIT(), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('airdrop_window_id', 'address')
    )
    op.create_index(op.f('ix_user_registrations_address'), 'user_registrations', ['address'], unique=False)
    op.create_table('user_rewards',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('airdrop_window_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('condition', sa.TEXT(), nullable=True),
    sa.Column('rewards_awarded', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_window_id'], ['airdrop_window.row_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('airdrop_window_id', 'address')
    )
    op.create_index(op.f('ix_user_rewards_address'), 'user_rewards', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rewards_address'), table_name='user_rewards')
    op.drop_table('user_rewards')
    op.drop_index(op.f('ix_user_registrations_address'), table_name='user_registrations')
    op.drop_table('user_registrations')
    op.drop_table('user_balance_snapshot')
    op.drop_index(op.f('ix_claim_history_address'), table_name='claim_history')
    op.drop_table('claim_history')
    op.drop_table('airdropwindow_rules')
    op.drop_table('airdrop_window')
    op.drop_table('airdrop')
    # ### end Alembic commands ###
